#!/home/tony/lib/miniforge3/envs/msm/bin/python

from pathlib import Path
from datetime import datetime as dt
import time
import sys
import os

HERE = Path(__file__).parent

def CurrentTimeMillis():
    return round(time.time() * 1000)

cache = HERE / "cache"
cache.mkdir(exist_ok=True)
fpath = cache / f"sbatch.{dt.now().strftime('%Y-%m-%d--%H-%M-%S')}"
SID = f"{CurrentTimeMillis()}"[-6:]

with open(fpath, "w") as f:
    with open(sys.argv[1], "r") as f2:
        for l in f2:
            f.write(l)
    f.write("# === command ===\n")
    f.write(" ".join(sys.argv) + "\n")
    f.write("# === slurm job id ===\n")
    f.write(f"{SID}\n")
    f.write("# === cwd ===\n")
    f.write(f"{Path('./').resolve()}\n")

import subprocess
entry = Path('./').resolve()/sys.argv[1]
subprocess.Popen(["bash", entry], start_new_session=True, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)

print(SID)
