#!/home/tony/lib/miniforge3/envs/msm/bin/python

from pathlib import Path
from datetime import datetime as dt
import time
import sys

HERE = Path(__file__).parent
cache = HERE / "cache"
fpath = cache / f"squeue.{dt.now().strftime('%Y-%m-%d--%H-%M-%S')}"

# 11199290 PD
# 11199290 R
# 11199290 CD
running_cache = cache/"running"
active: list[str] = []
for p in running_cache.iterdir():
    sid = str(p.name)
    active.append(sid)
    print(f"{sid} R")

with open(fpath, "w") as f:
    f.write("# === command ===\n")
    f.write("|".join(sys.argv) + "\n")
    f.write("# === cwd ===\n")
    f.write(f"{Path('./').resolve()}\n")
    f.write("# === active ===\n")
    f.write(f"n={len(active)}\n")
    f.write(f"{','.join(active)}\n")
