#!/bin/bash
# dev script version 1.1

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
NAME=metasmith
DEV_USER=hallamlab
_ver_file="$HERE/src/$NAME/version.txt"
_hash_file="$HERE/src/$NAME/build_hash.txt"
# version.txt holds the PEP 440 release segment (e.g. "0.18.2"). The build
# hash in build_hash.txt is regenerated by _build_hash.py at build time and
# identifies the exact source state. Together they form FULL_VER
# ("0.18.2+abc1234"); the docker tag is the same with '+' → '-'.
VER="$(cat $_ver_file)"
_compute_full_ver() {
    if [ -f "$_hash_file" ]; then
        echo "${VER}+$(cat $_hash_file)"
    else
        echo "${VER}"
    fi
}
FULL_VER="$(_compute_full_ver)"
DOCKER_TAG="${FULL_VER//+/-}"
DOCKER_IMAGE=quay.io/$DEV_USER/$NAME

# Refuse to publish or convert an image whose bundled relay binaries are
# stubs. Bug shipped in 0.18.4 where the Dockerfile happily COPYed 28-byte
# "#!/bin/sh\necho 'stub relay'" placeholders left over in main/relay_agent/
# target/ because the --update_container chain skips -br. Set
# MSM_SKIP_RELAY_CHECK=1 to override (e.g. emergency linux-only patch).
_assert_real_relays() {
    [ -n "$MSM_SKIP_RELAY_CHECK" ] && {
        echo "MSM_SKIP_RELAY_CHECK set — skipping relay binary check"
        return 0
    }
    local img="$DOCKER_IMAGE:$DOCKER_TAG"
    echo "checking relay binaries in $img"
    local out rc
    out=$(docker run --rm --entrypoint sh "$img" -c '
        bad=""
        for slot in x86_64-linux:7f454c46 arm64-linux:7f454c46 \
                    x86_64-darwin:cffaedfe arm64-darwin:cffaedfe; do
            tgt=${slot%:*}; want=${slot##*:}
            f=/app/msm_relay.$tgt
            sz=$(stat -c %s "$f" 2>/dev/null || echo 0)
            magic=$(head -c 4 "$f" 2>/dev/null | od -An -tx1 | tr -d " ")
            kind=stub
            case "$magic" in
                7f454c46) kind=ELF ;;
                cffaedfe|feedfacf) kind=Mach-O ;;
            esac
            ok=yes
            [ "$magic" = "$want" ] || ok=no
            [ "$sz" -gt 100000 ] || ok=no
            printf "  %-14s size=%-8s magic=%s  %s\n" "$tgt" "$sz" "$magic" "$kind"
            [ "$ok" = "yes" ] || bad="$bad $tgt"
        done
        [ -z "$bad" ] && exit 0
        echo "STUB:$bad"
        exit 1
    ' 2>&1)
    rc=$?
    echo "$out" | grep -v '^STUB:'
    if [ $rc -ne 0 ]; then
        local bad_slots
        bad_slots=$(echo "$out" | grep '^STUB:' | sed 's/^STUB://')
        echo ""
        echo "ERROR: stub relay binary detected in $img"
        echo "  bad slots:$bad_slots"
        echo ""
        echo "Rebuild relays first, then re-tag the image:"
        echo "  $HERE/dev.sh -brc   # build the cross-compile container (one time)"
        echo "  $HERE/dev.sh -br    # build all 4 relay targets"
        echo "  $HERE/dev.sh -bd    # rebuild the docker image"
        echo ""
        echo "Override (NOT recommended) by setting MSM_SKIP_RELAY_CHECK=1."
        return 1
    fi
    return 0
}

# CONDA=conda
CONDA=mamba # https://mamba.readthedocs.io/en/latest/mamba-installation.html#mamba-install
echo image: $DOCKER_IMAGE:$DOCKER_TAG
echo ""

# this file contains a list of commands useful for dev,
# providing automation for some build tasks
#
# example workflow 1, pip:
# dev.sh --idev # create a local conda dev env
# # add pypi api token as file to ./secrets [https://pypi.org/help/#apitoken]
# # make some changes to source
# # bump up ./src/*/version.txt
# dev.sh -bp # build the pip package
# dev.sh -up # test upload to testpypi
# dev.sh -upload-pypi # release to pypi index for pip install
#
# example workflow 2, conda:
# dev.sh --idev # create a local conda dev env
# dev.sh -bp # build the pip package
# dev.sh -bc # build conda package from pip package
# dev.sh -uc # publish to conda index
#
# example workflow 3, containerization:
# dev.sh --idev # create a local conda dev env
# dev.sh -bd # build docker image
# dev.sh -ud # publish to quay.io
# dev.sh -bs # build apptainer image from local docker image

case $1 in
    ###################################################
    # environments

    --idev) # with dev tools for packaging
        cd $HERE/envs
        echo "updating conda env: $2"
        echo "WARNING: you will need to install docker and apptainer individually"
        sleep 2
        $CONDA env update -n $2 -f ./dev.yml
    ;;
    --ibase) # base only
        cd $HERE/envs
        echo "creating new conda env: $NAME"
        sleep 2
        $CONDA env create --no-default-packages -n $NAME -f ./base.yml
    ;;
    --git-prune-local) # remove local branches not on remote
        git fetch -p
        git branch -r \
            | awk '{print $1}' \
            | egrep -v -f /dev/fd/0 <(git branch -vv \
            | grep origin) \
            | awk '{print $1}' \
            | xargs git branch -d
    ;;

    ###################################################
    # build
    -bp) # pip
        # build pip package
        [ -d ./build ] && rm -r build
        [ -d ./dist ] && rm -r dist
        # Stamp build_hash.txt before sdist/wheel so FULL_VERSION is baked in.
        PYTHONPATH="$HERE/src" python -m metasmith._build_hash --write >/dev/null
        FULL_VER="$(_compute_full_ver)"
        DOCKER_TAG="${FULL_VER//+/-}"
        echo "build hash: $(cat $_hash_file)"
        echo "full version: $FULL_VER"
        python -m build
    ;;
    -bpi) # pip - test install
        pip install $HERE/dist/$NAME-$FULL_VER-py3-none-any.whl --force-reinstall
    ;;
    -bpx) # pip - remove package
        pip uninstall -y $NAME
    ;;
    -bc) # conda
        # requires built pip package
        rm -r $HERE/conda_build
        python ./conda_recipe/compile_recipe.py
        $HERE/conda_recipe/call_build.sh
    ;;
    -brc) # build the container for building the relay
        cd $HERE/main/relay_agent
        ./dev.sh -bb
    ;;
    -br) # build the relay
        cd $HERE/main/relay_agent
        ./dev.sh -b
    ;;
    -bd) # docker
        # pre-download requirements
        mkdir -p $HERE/lib
        cd $HERE/lib
        TINI_VERSION=v0.19.0
        ! [ -f tini ] && wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini && chmod +x ./tini
        if ! [ -d globusconnectpersonal-latest ]; then
            wget -continue https://downloads.globus.org/globus-connect-personal/linux/stable/globusconnectpersonal-latest.tgz
            tar -xvf globusconnectpersonal-latest.tgz
            rm globusconnectpersonal-latest.tgz
            mv globusconnectpersonal-* globusconnectpersonal-latest
        fi
        NEXTFLOW_VERSION=$(cat ../envs/base.yml | grep nextflow | cut -c14- | xargs)
        echo "nextflow version: $NEXTFLOW_VERSION"
        ! [ -f nextflow ] && wget https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow && chmod +x ./nextflow
        cd $HERE

        # Stamp build_hash.txt so the image we tag matches FULL_VERSION exactly.
        PYTHONPATH="$HERE/src" python -m metasmith._build_hash --write >/dev/null
        FULL_VER="$(_compute_full_ver)"
        DOCKER_TAG="${FULL_VER//+/-}"
        echo image: $DOCKER_IMAGE:$DOCKER_TAG

        # build the docker container locally
        export DOCKER_BUILDKIT=1
        # --network=host because I ran into a network error
        docker build \
            --build-arg="CONDA_ENV=${NAME}_env" \
            --build-arg="PACKAGE=${NAME}" \
            --build-arg="VERSION=${FULL_VER}" \
            --network=host \
            -t $DOCKER_IMAGE:$DOCKER_TAG . \
        && docker inspect --format='{{.Size}}' $DOCKER_IMAGE:$DOCKER_TAG | numfmt --to=si
    ;;
    -bs) # apptainer image *from docker*
        _assert_real_relays || exit 1
        apptainer build --force $NAME.sif docker-daemon://$DOCKER_IMAGE:$DOCKER_TAG
    ;;
    --update_container)
        $HERE/dev.sh -bp && $HERE/dev.sh -bd && $HERE/dev.sh -ud && $HERE/dev.sh -bs
    ;;
    --update_conda)
        $HERE/dev.sh -bc && $HERE/dev.sh -uc
    ;;
    ###################################################
    # upload

    -up) # pip (testpypi)
        PYPI=testpypi
        TOKEN=$(cat secrets/${PYPI}) # https://pypi.org/help/#apitoken
        python -m twine upload --repository $PYPI dist/*.whl -u __token__ -p $TOKEN
    ;;
    -upload-pypi) # pip (pypi)
        echo "not all dependencies are available on pypi, so this is not a good idea..."
        # PYPI=pypi
        # TOKEN=$(cat secrets/${PYPI}) # https://pypi.org/help/#apitoken
        # python -m twine upload --repository $PYPI dist/*.whl -u __token__ -p $TOKEN
    ;;
    -uc) # conda (personal channel)
        # run `anaconda login` first
        find ./conda_build -name *.tar.bz2 | xargs -I % anaconda upload -u $DEV_USER %
    ;;
    -ud) # docker
        # login and push image to quay.io
        # sudo docker login quay.io
        _assert_real_relays || exit 1
	    docker push $DOCKER_IMAGE:$DOCKER_TAG
        echo "!!!"
        echo "remember to update the \"latest\" tag"
        echo "https://$DOCKER_IMAGE?tab=tags"
    ;;

    ###################################################
    # run

    -r)
        shift
        export PYTHONPATH=$HERE/src:$PYTHONPATH
        python -m $NAME $@
    ;;
    -rd) # docker
            # -e XDG_CACHE_HOME="/ws"\
        shift
        mkdir -p ./scratch/docker
        cd ./scratch/docker
        # mkdir -p cache/.globus cache/.globusonline
        docker run -it --rm \
            -u $(id -u):$(id -g) \
            --mount type=bind,source="/tmp",target="/tmp"\
            --mount type=bind,source="$HERE/scratch/docker",target="/ws"\
            --mount type=bind,source="$HOME/.globus",target="/.globus"\
            --mount type=bind,source="$HOME/.globusonline",target="/.globusonline"\
            --workdir="/ws" \
            $DOCKER_IMAGE:$DOCKER_TAG /bin/bash
    ;;
    -rs) # apptainer
            # -e XDG_CACHE_HOME="/ws"\
        shift
        mkdir -p ./scratch/docker
        cd ./scratch/docker
        apptainer exec \
            --bind ./:/ws \
            --workdir /ws \
            --no-home \
            $HERE/$NAME.sif /bin/bash
            # docker-daemon://$DOCKER_IMAGE:$DOCKER_TAG /bin/bash
    ;;

    ###################################################
    # test

    -t)
        shift
        export PYTHONPATH=$HERE/src:$PYTHONPATH
        ws=$HERE/scratch/test_ws
        mkdir -p $ws
        cd $ws
        python -m $NAME lab $@
    ;;

    -tt)
        shift
        cd $HERE
        export PYTHONPATH=$HERE/src:$PYTHONPATH
        pytest $@
    ;;

    -td) # inject updates to an agent home for dev binds
        shift
        export PYTHONPATH=$HERE/src:$HERE/lib:$PYTHONPATH
        python3 main/local_mock/rsync.py $@
    ;;

    -t2)
        cd ./main/relay_agent/scratch/cache/mock
        # mkdir -p cache/.globus cache/.globusonline
        docker run -it --rm \
            -u $(id -u):$(id -g) \
            -e NXF_HOME="/ws/.nextflow" \
            --mount type=bind,source="$HERE/main/local_mock/cache/local_home/runs/dwfuH8Cz",target="/ws"\
            --mount type=bind,source="$HERE/main/local_mock/cache/local_home",target="/msm_home"\
            --mount type=bind,source="$HOME/.globus",target="/.globus"\
            --mount type=bind,source="$HOME/.globusonline",target="/.globusonline"\
            --workdir="/ws" \
            $DOCKER_IMAGE:$DOCKER_TAG /bin/bash
    ;;

    ###################################################
    # docs

    --docs) # build docs
        shift
        cd $HERE/docs
        sphinx-autobuild -a ./source ./build/html
    ;;

    ###################################################

    *)
        echo "bad option"
        echo $1
    ;;
esac
