"""Regression test: dev.sh refuses to package without a fresh vendored library.

`src/metasmith/vendor/metasmith_libraries/` is generated by `--vendor-library`
and never committed, so a fresh checkout -- or one where the library moved on
since the last vendor run -- has none or a stale one. Skip that step and
`-bp`/`-bc`/`-bd` would happily ship a wheel/conda package/image without the
pinned standard library; `clone_stdlib`'s live GitHub clone masks the gap until
someone builds offline. Same shape as the stub-relay and missing-GUI bugs,
guarded the same way.
"""

import shutil
import subprocess
import textwrap
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
DEV_SH = REPO_ROOT / "dev" / "metasmith.sh"


def _run_guard(tmp_path: Path, *, bundle: bool):
    """Source dev.sh, point HERE/_lib_vendor at a fake repo, and stub `python`
    so the guard's `python -m metasmith build vendor-library ... --check` call
    doesn't need a real metasmith install. The CLI-level hashing/staleness
    logic is covered directly against the real package elsewhere; this test is
    only responsible for the guard's own wiring, messages, and exit code."""
    fake_here = tmp_path / "repo"
    dst = fake_here / "src" / "metasmith" / "vendor" / "metasmith_libraries"
    dst.mkdir(parents=True)
    if bundle:
        (dst / "VENDOR_HASH").write_text("abc1234")

    stub_dir = tmp_path / "bin"
    stub_dir.mkdir()
    py_stub = stub_dir / "python"
    py_stub.write_text(textwrap.dedent(f"""\
        #!/bin/sh
        if [ -f "{dst}/VENDOR_HASH" ]; then
            echo "dst: {dst}"
            echo "ok: True"
            exit 0
        fi
        echo "no vendored bundle at [{dst}] (missing VENDOR_HASH)" >&2
        exit 1
    """))
    py_stub.chmod(0o755)

    script = textwrap.dedent(f"""
        set -e
        source {DEV_SH} >/dev/null 2>&1 || true
        HERE={fake_here}
        NAME=metasmith
        _lib_vendor={dst}
        export PATH={stub_dir}:$PATH
        _assert_library_bundle
    """)
    return subprocess.run(["bash", "-c", script], capture_output=True, text=True, timeout=20)


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
@pytest.mark.skipif(shutil.which("bash") is None, reason="bash required")
def test_guard_passes_with_a_bundle(tmp_path):
    proc = _run_guard(tmp_path, bundle=True)
    assert proc.returncode == 0, f"stdout={proc.stdout!r} stderr={proc.stderr!r}"


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
@pytest.mark.skipif(shutil.which("bash") is None, reason="bash required")
def test_guard_blocks_without_a_bundle(tmp_path):
    proc = _run_guard(tmp_path, bundle=False)
    assert proc.returncode != 0
    assert "vendored standard library" in proc.stdout
    assert "--vendor-library" in proc.stdout


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
@pytest.mark.skipif(shutil.which("bash") is None, reason="bash required")
def test_guard_can_be_overridden(tmp_path):
    fake_here = tmp_path / "repo"
    (fake_here / "src").mkdir(parents=True)
    script = textwrap.dedent(f"""
        source {DEV_SH} >/dev/null 2>&1 || true
        HERE={fake_here}
        NAME=metasmith
        export MSM_SKIP_LIBRARY_CHECK=1
        _assert_library_bundle
    """)
    proc = subprocess.run(["bash", "-c", script], capture_output=True, text=True, timeout=20)
    assert proc.returncode == 0, f"stdout={proc.stdout!r} stderr={proc.stderr!r}"
    assert "skipping vendored-library check" in proc.stdout


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
def test_packaging_steps_call_the_guard():
    """The guard is worthless if the build steps do not run it."""
    text = DEV_SH.read_text()
    for step in ("-bp) # pip", "-bc) # conda", "-bd) # docker"):
        i = text.index(step)
        body = text[i : i + 600]
        assert "_assert_library_bundle" in body, f"{step} does not check the vendored library"
