"""The on-wire lin-envelope version must stay synced across its two writers.

There are two independent statements of the Nextflow-channel lin-envelope
version, and a real task fails at runtime the moment they disagree:

  1. the PARSER — `models.lineage.LinPayload` (`VERSION` / `Unpack`), which
     rejects any payload whose `v` != `LIN_PAYLOAD_VERSION`; and
  2. the EMITTER — a Groovy literal generated by `workflow.py` into every
     compiled `workflow.nf`:
        echo "lin ${Orchestrator.JsonforEcho([v:N, entries:index[0]])}"

These live in different files and are NOT type-checked against each other.
The fast test suite cannot catch a desync because its harnesses synthesize
lin payloads via `json.dumps`, never through the Groovy wire — so a mismatch
only surfaces in a real docker/apptainer deploy, where it fails EVERY task
with `unsupported lin payload version <emitted>; expected <parser>`.

That is exactly what happened in R5: bumping the (then-shared) version
constant for the F1 cache-key change moved the parser to 3 while the Groovy
emitter stayed hardcoded at 2. The cache-key epoch and the wire version are
now separate constants (`CACHE_KEY_VERSION` vs `LIN_PAYLOAD_VERSION`); this
test pins the wire invariant so the split cannot silently rot: a future edit
to either the emitter literal or the parser constant must move the other.
"""

from __future__ import annotations

import re
from pathlib import Path

from metasmith.caching.keys import CACHE_KEY_VERSION, LIN_PAYLOAD_VERSION
from metasmith.models.lineage import LinPayload
import metasmith.models.workflow as workflow_mod


# `[v:2, entries:...]` — the version the Groovy emitter stamps onto the wire.
_EMITTER_RE = re.compile(r"\[\s*v\s*:\s*(\d+)\s*,\s*entries\s*:")


def _emitter_wire_versions() -> list[int]:
    # Scan the whole package, not one module. The emitter used to sit in
    # workflow.py; it now lives in workflow/nextflow_codegen.py, and reading
    # `workflow_mod.__file__` after the split would have read an __init__ of
    # pure re-exports -- no literals, and this guard blind to the one desync
    # it exists to catch. Globbing keeps it honest through the next move too.
    pkg = Path(workflow_mod.__file__).parent
    found: list[int] = []
    for src in sorted(pkg.rglob("*.py")):
        found += [int(m) for m in _EMITTER_RE.findall(src.read_text(encoding="utf-8"))]
    return found


def test_groovy_emitter_matches_parser_version():
    """Every `[v:N, entries:...]` the compiler emits must equal the parser's."""
    emitted = _emitter_wire_versions()
    assert emitted, (
        "no `[v:N, entries:...]` lin-envelope emitter literal found in "
        "workflow.py; the regex guard is stale — update it to track the "
        "current emitter so this invariant keeps being checked"
    )
    for n in emitted:
        assert n == LIN_PAYLOAD_VERSION, (
            f"Groovy lin emitter stamps wire version {n} but the parser "
            f"(LinPayload) expects {LIN_PAYLOAD_VERSION}; a real deploy would "
            f"fail every task with 'unsupported lin payload version'. Move the "
            f"emitter literal and LIN_PAYLOAD_VERSION together."
        )


def test_parser_classvar_tracks_module_constant():
    """LinPayload.VERSION must equal the wire constant it is built from."""
    assert LinPayload.VERSION == LIN_PAYLOAD_VERSION


def test_cache_epoch_and_wire_version_are_independent():
    """The two concerns are separate constants (regression guard for R5).

    They are not required to hold any particular relative value — only to be
    distinct symbols so a cache-semantics bump never again drags the wire
    version (and its un-synced Groovy emitter) along with it. Pinning the
    known post-R5 values documents the split and flags any accidental re-merge.
    """
    assert CACHE_KEY_VERSION == 3
    assert LIN_PAYLOAD_VERSION == 2
