"""The on-wire lin-envelope version must stay synced across its two writers.

There are two independent statements of the Nextflow-channel lin-envelope
version, and a real task fails at runtime the moment they disagree:

  1. the PARSER — `models.lineage.LinPayload` (`VERSION` / `Unpack`), which
     rejects any payload whose `v` != `LIN_PAYLOAD_VERSION`; and
  2. the EMITTER — a Groovy literal generated by `workflow.py` into every
     compiled `workflow.nf`:
        echo "lin ${Orchestrator.JsonforEcho([v:N, entries:index])}"

These live in different files and are NOT type-checked against each other.
The fast test suite cannot catch a desync because its harnesses synthesize
lin payloads via `json.dumps`, never through the Groovy wire — so a mismatch
only surfaces in a real docker/apptainer deploy, where it fails EVERY task
with `unsupported lin payload version <emitted>; expected <parser>`.

That is exactly what happened in R5: bumping the (then-shared) version
constant for the F1 cache-key change moved the parser to 3 while the Groovy
emitter stayed hardcoded at 2. The cache-key epoch and the wire version are
now separate constants (`CACHE_KEY_VERSION` vs `LIN_PAYLOAD_VERSION`).

The emitter no longer spells the version as a literal — it interpolates
`LIN_PAYLOAD_VERSION` into `nextflow_codegen.LIN_ECHO_EXPR`, so the desync is
unrepresentable rather than merely detected. These tests pin that: the
rendered expression must stamp the parser's version, and no module in the
workflow package may reintroduce a hardcoded one.
"""

from __future__ import annotations

import re
from pathlib import Path

from metasmith.caching.keys import CACHE_KEY_VERSION, LIN_PAYLOAD_VERSION
from metasmith.models.lineage import LinPayload
from metasmith.models.workflow.nextflow_codegen import LIN_ECHO_EXPR
import metasmith.models.workflow as workflow_mod


# `[v:2, entries:...]` — the version the Groovy emitter stamps onto the wire.
_EMITTER_RE = re.compile(r"\[\s*v\s*:\s*(\d+)\s*,\s*entries\s*:")


def _hardcoded_wire_versions() -> list[int]:
    # Scan the whole package, not one module. The emitter used to sit in
    # workflow.py; it now lives in workflow/nextflow_codegen.py, and reading
    # `workflow_mod.__file__` after the split would have read an __init__ of
    # pure re-exports -- no literals, and this guard blind to the one desync
    # it exists to catch. Globbing keeps it honest through the next move too.
    pkg = Path(workflow_mod.__file__).parent
    found: list[int] = []
    for src in sorted(pkg.rglob("*.py")):
        found += [int(m) for m in _EMITTER_RE.findall(src.read_text(encoding="utf-8"))]
    return found


def test_rendered_emitter_stamps_the_parser_version():
    """The expression the compiler emits carries `LIN_PAYLOAD_VERSION`."""
    found = _EMITTER_RE.findall(LIN_ECHO_EXPR)
    assert found, (
        f"no `[v:N, entries:...]` envelope in the rendered emitter "
        f"{LIN_ECHO_EXPR!r}; the guard is stale — update it to track the "
        f"current emitter so this invariant keeps being checked"
    )
    for n in found:
        assert int(n) == LIN_PAYLOAD_VERSION, (
            f"Groovy lin emitter stamps wire version {n} but the parser "
            f"(LinPayload) expects {LIN_PAYLOAD_VERSION}; a real deploy would "
            f"fail every task with 'unsupported lin payload version'."
        )


def test_no_module_hardcodes_the_wire_version():
    """The version must be interpolated, never typed as a literal."""
    assert _hardcoded_wire_versions() == [], (
        "a module in metasmith.models.workflow spells the lin-envelope "
        "version as a literal. Interpolate LIN_PAYLOAD_VERSION instead — a "
        "literal is how R5 desynced the emitter from the parser and failed "
        "every containerized task with a green fast suite."
    )


def test_parser_classvar_tracks_module_constant():
    """LinPayload.VERSION must equal the wire constant it is built from."""
    assert LinPayload.VERSION == LIN_PAYLOAD_VERSION


def test_cache_epoch_and_wire_version_are_independent():
    """The two concerns are separate constants (regression guard for R5).

    They are not required to hold any particular relative value — only to be
    distinct symbols so a cache-semantics bump never again drags the wire
    version (and its un-synced Groovy emitter) along with it. Pinning the
    known post-R5 values documents the split and flags any accidental re-merge.
    """
    assert CACHE_KEY_VERSION == 3
    assert LIN_PAYLOAD_VERSION == 3
