ARG CONDA_ENV=for_container

# https://github.com/conda-forge/miniforge/releases
# https://sourceware.org/glibc/wiki/Glibc%20Timeline
# glibc 2.34 for sockeye
# FROM condaforge/miniforge3:4.10.3-4
FROM condaforge/miniforge3
# scope var from global
ARG CONDA_ENV

# I believe this is to avoid permission issues with 
# manipulating added files to places like /opt
RUN old_umask=`umask` \
    && umask 0000 \
    && umask $old_umask

RUN apt-get update && apt-get install -y \
    binutils

# https://mamba.readthedocs.io/en/latest/user_guide/mamba.html
# create conda env from yaml config
COPY ./base.yml /opt/base.yml
# use an external cache for solved environments and install packages
RUN --mount=type=cache,target=/opt/conda/pkgs \
    mamba env create -n ${CONDA_ENV} --no-default-packages -f /opt/base.yml
# add bins to PATH so that the env appears "active"
ENV PATH /opt/conda/envs/${CONDA_ENV}/bin:/app:$PATH
