<script>
  import { api } from '../lib/api.js'
  import { attempt } from '../lib/state.svelte.js'
  import Field from './Field.svelte'

  // One control with two states. With no key, it offers to make one; once it
  // has made one, the same button becomes the way to take it back -- double
  // click to confirm, as everywhere else that destroys something.
  //
  // Delete is offered only for a key metasmith generated and that is still on
  // disk. Point the field at your own key and the button goes away: that one is
  // not ours to remove, and the backend refuses it regardless.
  let { alias, value = $bindable(''), identity = null, onchange } = $props()

  let busy = $state(false)
  let armed = $state(false)
  let timer

  let ours = $derived(
    !!identity && identity.generated && identity.exists && identity.value === value,
  )

  function disarm() {
    clearTimeout(timer)
    armed = false
  }

  async function generate() {
    if (!alias?.trim()) return
    busy = true
    const out = await attempt(() => api.post('/ssh/keys', { alias: alias.trim() }))
    busy = false
    if (!out) return
    value = out.value
    onchange?.(out)
  }

  async function remove() {
    if (!armed) {
      armed = true
      timer = setTimeout(() => (armed = false), 2000)
      return
    }
    disarm()
    busy = true
    const out = await attempt(() => api.del(`/ssh/keys/${alias}`))
    busy = false
    if (!out) return
    value = ''
    onchange?.(null)
  }
</script>

<Field
  label="identity file"
  hint={ours
    ? 'generated by metasmith — deleting it removes the key from disk'
    : 'the private key to authenticate with; generating one puts it in ~/.ssh/metasmith'}
>
  <div class="row">
    <input class="grow" bind:value oninput={disarm} />
    {#if ours}
      <button
        class="danger"
        class:armed
        onclick={remove}
        disabled={busy}
        title={armed ? 'click again to confirm' : 'delete this key from disk'}
      >
        {armed ? 'confirm?' : 'delete'}
      </button>
    {:else}
      <button
        onclick={generate}
        disabled={busy || !alias?.trim()}
        title={alias?.trim() ? 'create a new ed25519 key for this alias' : 'name the host first'}
      >
        {busy ? 'working…' : 'generate'}
      </button>
    {/if}
  </div>
</Field>

<style>
  button { white-space: nowrap; }
  .armed { color: var(--bad); border-color: var(--bad); }
</style>
