"""Regression test: dev.sh refuses to package without a built GUI bundle.

`src/metasmith/gui/static/` is generated by `--build-gui` and never committed,
so a fresh checkout has none. Skip that step and `-bp`/`-bd` happily produce a
wheel and an image whose static directory is empty — the server then serves
nothing, and the failure is invisible until someone opens the page. Same shape
as the stub-relay bug in 0.18.4, and guarded the same way.
"""

import shutil
import subprocess
import textwrap
from pathlib import Path

import pytest


# the GUI's own suite: `dev.sh -tg` runs exactly the files carrying this,
# and it is the inner loop while working on the page -- keep it fast.
pytestmark = pytest.mark.gui

REPO_ROOT = Path(__file__).resolve().parents[1]
DEV_SH = REPO_ROOT / "dev.sh"


def _run_guard(tmp_path: Path, *, bundle: bool):
    fake_here = tmp_path / "repo"
    static = fake_here / "src" / "metasmith" / "gui" / "static"
    static.mkdir(parents=True)
    if bundle:
        (static / "index.html").write_text("<!doctype html>")
        (static / "assets").mkdir()
        (static / "assets" / "index.js").write_text("// bundle")

    script = textwrap.dedent(f"""
        set -e
        source {DEV_SH} >/dev/null 2>&1 || true
        HERE={fake_here}
        NAME=metasmith
        _gui_static="$HERE/$NAME/gui/static"
        _gui_static={static}
        _assert_gui_bundle
    """)
    return subprocess.run(["bash", "-c", script], capture_output=True, text=True, timeout=20)


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
@pytest.mark.skipif(shutil.which("bash") is None, reason="bash required")
def test_guard_passes_with_a_bundle(tmp_path):
    proc = _run_guard(tmp_path, bundle=True)
    assert proc.returncode == 0, f"stdout={proc.stdout!r} stderr={proc.stderr!r}"
    assert "gui bundle:" in proc.stdout


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
@pytest.mark.skipif(shutil.which("bash") is None, reason="bash required")
def test_guard_blocks_without_a_bundle(tmp_path):
    proc = _run_guard(tmp_path, bundle=False)
    assert proc.returncode != 0
    assert "GUI bundle is missing" in proc.stdout
    assert "--build-gui" in proc.stdout


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
@pytest.mark.skipif(shutil.which("bash") is None, reason="bash required")
def test_guard_can_be_overridden(tmp_path):
    fake_here = tmp_path / "repo"
    (fake_here / "src").mkdir(parents=True)
    script = textwrap.dedent(f"""
        source {DEV_SH} >/dev/null 2>&1 || true
        HERE={fake_here}
        NAME=metasmith
        export MSM_SKIP_GUI_CHECK=1
        _assert_gui_bundle
    """)
    proc = subprocess.run(["bash", "-c", script], capture_output=True, text=True, timeout=20)
    assert proc.returncode == 0
    assert "skipping GUI bundle check" in proc.stdout


@pytest.mark.skipif(not DEV_SH.exists(), reason="dev.sh missing")
def test_packaging_steps_call_the_guard():
    """The guard is worthless if the build steps do not run it."""
    text = DEV_SH.read_text()
    for step in ("-bp) # pip", "-bd) # docker"):
        i = text.index(step)
        body = text[i : i + 400]
        assert "_assert_gui_bundle" in body, f"{step} does not check the GUI bundle"
