channels:
  - conda-forge
dependencies:
  # - pyinstaller=6.11.1
  - setuptools<81 # important, also [--exclude-module pkg_resources]; https://github.com/yt-dlp/yt-dlp/issues/13311
  - python=3.12

  - pip
  - pip:
    # why does numpy only work when installed thorugh pip???
    # otherwise:
    # ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
    - numpy==2.2.5
    - pyinstaller==6.11.1

  # alternative to flask-socketio is flask-sock
  # provides low level sockets, which would connect to unix file sockets
  # but is low level, as in packet = read(length)
  # -c delichon

  # # for ws
  # - fastapi=0.121 # for lifespan events, no endpoints
  # - uvicorn=0.38
  # - uvicorn-standard=0.38

  # - python-socketio=5.14.2
  # - python-engineio=4.12.3
  # - websocket-client=1.9.0
  # - requests=2.32.3
  # - aiohttp=3.13.1
