#!/bin/bash

HERE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
mkdir -p $HERE/cache
fpath=$HERE/cache/$(date +%Y-%m-%d--%H-%M-%S)
touch $fpath
echo $@ >> $fpath
echo "" >> $fpath
cat $1 >> $fpath

echo 123
