channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - nextflow=26.04.1
  - graphviz=13.1.1 # DAG renderer
  - python-graphviz=0.21 # Python bindings
  - pyyaml=6.0.2
  - numpy=2.2.5
  - rsync=3.4.1
  - pigz=2.8
  - unzip=6.0
  - git=2.52.0 # to pull transform libraries
  - tk=8.6.13 # for globus
  - git # to pull transforms

  # # relay now just uses files
  # # networking (mostly for relay)
  # - python-socketio=5.14.2
  # - python-engineio=4.12.3
  # - websocket-client=1.9.0
  # - requests=2.32.3
  # - aiohttp=3.13.1
  
  # UI via jupyterlab
  - jupyterlab=4.5.0
  - jupyterlab-lsp=5.2.0
  - python-lsp-server=1.13.2
  - jupyterlab-unfold=0.3.4
  - theme-material-darcula=1.0.3

  # common tools (not strictly dependencies)
  - pandas=2.3.3
  - openpyxl=3.1.5  # for pandas to read excel files
  - plotly=6.5.0
  - scipy=1.16.3
  
  # globus
  - globus-cli=3.40.0
  - globus-sdk=4.1.0

# there can NOT be any pip dependencies,
# since those will not be installed with the conda package
