channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - nextflow=24.10.5
  - graphviz=13.1.1 # DAG renderer
  - python-graphviz=0.21 # Python bindings
  - pyyaml=6.0.2
  - numpy=2.2.5
  - rsync=3.4.1
  - pigz=2.8

  - python-socketio=5.14.2
  - python-engineio=4.12.3
  - websocket-client=1.9.0
  - requests=2.32.3
  - aiohttp=3.13.1
  
  - pip
  - pip:
      - globus-cli==3.32.0
      - globus-sdk==3.46.0
