set -euo pipefail
DEST=/home/phyberos/project-rpp/steven_c_gmcf3495/metagenomics
ARB=/scratch/phyberos/gmcf3495/.publish_arbutus
STAGE=$(mktemp -d /scratch/phyberos/.publish.XXXXXX)
trap "rm -rf $STAGE" EXIT

mkdir -p "$DEST"/reads/interleaved
mkdir -p "$DEST"/reads/qc_stats
mkdir -p "$DEST"/taxonomy_reads/bracken_kreport
mkdir -p "$DEST"/taxonomy_reads/bracken_species
mkdir -p "$DEST"/taxonomy_reads/centrifuger_classifications
mkdir -p "$DEST"/taxonomy_reads/centrifuger_kreport
mkdir -p "$DEST"/taxonomy_reads/centrifuger_summary
mkdir -p "$DEST"/taxonomy_reads/kraken2_classifications
mkdir -p "$DEST"/taxonomy_reads/kraken2_report

cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.0VfzvJWdknZPJFgy-RohhQFjN.fq.gz "$DEST"/reads/interleaved/NTC.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.1yhRfb23RzUd4iU5-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S28.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.3KOUweyBl8EbC37i-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S20.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.4LivI2qF6nQ0g6hi-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S26.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.5L7plJK7KoUHYBrc-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S11.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.BrgvYV4bksugid5K-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S2.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.CEPNkP3djLbF1a4c-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S24.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.ClzuA45gFfYGa4OC-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S9.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.IxcbKN8xKbb2LFuz-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S3.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.JZ2ao2vSVftn1tmM-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S32.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.LdtwVSGjyfVMg23s-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S23.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.MbhITNXdkxvPKGfs-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S6.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.QOTDnidJ9lByNc7y-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S25.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.QklBXQgP2QFZv9Ze-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S8.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.SnPdwxepFipTP6fQ-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S14.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.TM0TJzwkzYhQz8vO-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S13.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.V2bVmlHdVTTPu7C4-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S16.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.X9tFaexu0G0BDtTv-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S19.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.Xa23GR7ltX1EMCaq-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S12.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.ZJ2SGey17DpJpgmG-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S29.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.ZoDf6dZEoZKHIMZH-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S4.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.cx5YyqKikBXCDIgb-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S22.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.dkxUd6oX3A1OfOjr-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S27.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.ht35i4w4poYLcZKA-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S17.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.k4fdE5Ly8YhbqO1Y-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S5.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.p1QnjaK0pZTPHSOO-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S7.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.pTyFOFXUKR9VRJhF-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S1.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.q0BoI0MIToSUMnVL-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S33.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.qH3Bq7v4cXhkGLAf-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S10.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.vZleBNrOn2qClpIr-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S18.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.wE2wf498KZm7WPgc-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S31.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.xVuoJ7ITKW5iVBWQ-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S15.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.zERBWmwtz19RsOuH-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S30.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/1_sequences-short_reads/1-1-1.zPUGC9JfHEVjWc2C-RohhQFjN.fq.gz "$DEST"/reads/interleaved/S21.fq.gz
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.0lhx9L7ESzbqwRvO-HAd1j0iE.json "$DEST"/reads/qc_stats/S10.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.43m4EUl7JcJZxetZ-HAd1j0iE.json "$DEST"/reads/qc_stats/S8.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.7ywvZvwwIvowYIlc-HAd1j0iE.json "$DEST"/reads/qc_stats/S29.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.BACcJkTxWSoLnUg1-HAd1j0iE.json "$DEST"/reads/qc_stats/S11.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.CD6QZpjNMxRy2BPt-HAd1j0iE.json "$DEST"/reads/qc_stats/S24.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.CWEUjZcYlFLsmIdL-HAd1j0iE.json "$DEST"/reads/qc_stats/S21.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.FFksa7f4386drlu3-HAd1j0iE.json "$DEST"/reads/qc_stats/S5.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.IzegYHTs976DEGdA-HAd1j0iE.json "$DEST"/reads/qc_stats/S23.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.LDYTioCZvLduINZA-HAd1j0iE.json "$DEST"/reads/qc_stats/S15.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.LNk3O4tSKzI8rL9u-HAd1j0iE.json "$DEST"/reads/qc_stats/S26.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.OQAfa5L53OPTxmyh-HAd1j0iE.json "$DEST"/reads/qc_stats/S30.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.P29oe1y1H8NiuGkv-HAd1j0iE.json "$DEST"/reads/qc_stats/S4.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.PkimTfaEniSFqsdN-HAd1j0iE.json "$DEST"/reads/qc_stats/S17.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.PzWGcdbrENYnIEsl-HAd1j0iE.json "$DEST"/reads/qc_stats/S33.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.QLVpFAPfSc0Wb2iw-HAd1j0iE.json "$DEST"/reads/qc_stats/S1.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.QQPjJFqnviKKDdns-HAd1j0iE.json "$DEST"/reads/qc_stats/S19.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.QQTrU8TKInNUYeoO-HAd1j0iE.json "$DEST"/reads/qc_stats/NTC.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.QX1uCKm9RNmRtfAx-HAd1j0iE.json "$DEST"/reads/qc_stats/S6.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.R2YM4kqhMat1tSDX-HAd1j0iE.json "$DEST"/reads/qc_stats/S25.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.RJslMZLJ1A0JGMxw-HAd1j0iE.json "$DEST"/reads/qc_stats/S18.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.S2Fy1aDDtFSwvBNP-HAd1j0iE.json "$DEST"/reads/qc_stats/S13.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.Slp2zAk0cuYifAEl-HAd1j0iE.json "$DEST"/reads/qc_stats/S27.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.XWXfrEsWbQLdMO4D-HAd1j0iE.json "$DEST"/reads/qc_stats/S3.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.ZMmuxNE2X321lGae-HAd1j0iE.json "$DEST"/reads/qc_stats/S22.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.Zo5ifukfMkVkjzFe-HAd1j0iE.json "$DEST"/reads/qc_stats/S16.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.gVVBUR8o37O955bo-HAd1j0iE.json "$DEST"/reads/qc_stats/S2.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.mc8I4AjkmrBUk49V-HAd1j0iE.json "$DEST"/reads/qc_stats/S20.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.pVBNjuotPj26YKHX-HAd1j0iE.json "$DEST"/reads/qc_stats/S14.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.rkqeraU9nB2D79Rw-HAd1j0iE.json "$DEST"/reads/qc_stats/S7.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.rngFrsO4eNgfgh74-HAd1j0iE.json "$DEST"/reads/qc_stats/S32.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.tzI2Z7R08UsWbSsM-HAd1j0iE.json "$DEST"/reads/qc_stats/S9.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.tzRPVczh5iORmfyC-HAd1j0iE.json "$DEST"/reads/qc_stats/S31.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.yZNYTvf1iyHHfSU6-HAd1j0iE.json "$DEST"/reads/qc_stats/S12.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/sequences-read_qc_stats/1-1-1.z6MlKJdtSC7Lyht2-HAd1j0iE.json "$DEST"/reads/qc_stats/S28.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.01HCK9dZAMAbMukq-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S25.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.2xIMBGbiOseSxQCD-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S11.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.4B6fy8hZZ8vSXE6B-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S5.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.4xCV6JRU6HkGatYq-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S20.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.7rMQZ4Ula2DmGaEd-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/NTC.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.9AjOqVTJNROY7DBG-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S2.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.AXK1NbQNocBd4qqI-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S14.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.CNI1jcL33E2M2uV6-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S19.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.E7S5GJo5ekcoOV27-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S33.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.FKp680zKVo15dKgx-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S21.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.IPNSBGNPpc9mx9pb-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S9.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.JY18N2LHdJyyKRwd-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S16.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.Pa6ucpXzUxAcuJtu-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S17.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.QgjOzZ09l9i6knsR-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S1.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.Qr8WER28PwzTwUhF-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S4.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.SE6URQqgwsDooLq4-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S26.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.UuWOdRNf2iRU3a0s-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S3.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.Vneit8ULTahKdRZb-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S29.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.W6RLtc1JWrQak6xQ-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S28.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.X9ogN7cwWyqV1rpF-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S30.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.XRi701FcJjjCcIJE-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S7.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.as0LFV4jcZBVeaAT-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S15.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.btskgvYgpK5TkYCK-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S27.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.mDxVGaoPbZ5795FZ-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S24.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.mEiZZ5B1TErMYJfM-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S18.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.nCeLnPSiD1XZVwqJ-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S13.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.nXQanJEGt3xJDy8L-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S8.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.o3c9CZgtU9S2sjB0-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S32.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.oEtMqfWVbBxXHV95-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S12.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.oP1PiCLDlN0wkUGY-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S31.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.onKJTzIZowunFZQ0-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S23.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.qN0TocA9AAHxywJY-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S10.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.tdiMdWfixh6fjadZ-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S22.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-kraken2_classifications/1-1-1.xZvD8e7qQi8PUA2N-cD8zPnH4.parquet "$DEST"/taxonomy_reads/kraken2_classifications/S6.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.01HCK9dZAMAbMukq-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S25.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.2xIMBGbiOseSxQCD-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S11.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.4B6fy8hZZ8vSXE6B-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S5.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.4xCV6JRU6HkGatYq-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S20.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.7rMQZ4Ula2DmGaEd-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/NTC.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.9AjOqVTJNROY7DBG-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S2.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.AXK1NbQNocBd4qqI-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S14.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.CNI1jcL33E2M2uV6-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S19.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.E7S5GJo5ekcoOV27-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S33.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.FKp680zKVo15dKgx-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S21.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.IPNSBGNPpc9mx9pb-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S9.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.JY18N2LHdJyyKRwd-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S16.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.Pa6ucpXzUxAcuJtu-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S17.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.QgjOzZ09l9i6knsR-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S1.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.Qr8WER28PwzTwUhF-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S4.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.SE6URQqgwsDooLq4-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S26.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.UuWOdRNf2iRU3a0s-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S3.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.Vneit8ULTahKdRZb-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S29.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.W6RLtc1JWrQak6xQ-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S28.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.X9ogN7cwWyqV1rpF-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S30.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.XRi701FcJjjCcIJE-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S7.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.as0LFV4jcZBVeaAT-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S15.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.btskgvYgpK5TkYCK-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S27.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.mDxVGaoPbZ5795FZ-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S24.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.mEiZZ5B1TErMYJfM-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S18.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.nCeLnPSiD1XZVwqJ-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S13.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.nXQanJEGt3xJDy8L-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S8.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.o3c9CZgtU9S2sjB0-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S32.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.oEtMqfWVbBxXHV95-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S12.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.oP1PiCLDlN0wkUGY-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S31.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.onKJTzIZowunFZQ0-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S23.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.qN0TocA9AAHxywJY-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S10.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.tdiMdWfixh6fjadZ-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S22.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-kraken2_report/1-1-1.xZvD8e7qQi8PUA2N-maz6nFbQ.tsv "$DEST"/taxonomy_reads/kraken2_report/S6.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.01HCK9dZAMAbMukq-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S25.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.2xIMBGbiOseSxQCD-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S11.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.4B6fy8hZZ8vSXE6B-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S5.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.4xCV6JRU6HkGatYq-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S20.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.7rMQZ4Ula2DmGaEd-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/NTC.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.9AjOqVTJNROY7DBG-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S2.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.AXK1NbQNocBd4qqI-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S14.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.CNI1jcL33E2M2uV6-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S19.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.E7S5GJo5ekcoOV27-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S33.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.FKp680zKVo15dKgx-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S21.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.IPNSBGNPpc9mx9pb-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S9.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.JY18N2LHdJyyKRwd-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S16.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.Pa6ucpXzUxAcuJtu-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S17.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.QgjOzZ09l9i6knsR-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S1.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.Qr8WER28PwzTwUhF-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S4.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.SE6URQqgwsDooLq4-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S26.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.UuWOdRNf2iRU3a0s-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S3.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.Vneit8ULTahKdRZb-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S29.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.W6RLtc1JWrQak6xQ-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S28.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.X9ogN7cwWyqV1rpF-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S30.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.XRi701FcJjjCcIJE-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S7.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.as0LFV4jcZBVeaAT-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S15.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.btskgvYgpK5TkYCK-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S27.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.mDxVGaoPbZ5795FZ-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S24.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.mEiZZ5B1TErMYJfM-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S18.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.nCeLnPSiD1XZVwqJ-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S13.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.nXQanJEGt3xJDy8L-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S8.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.o3c9CZgtU9S2sjB0-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S32.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.oEtMqfWVbBxXHV95-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S12.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.oP1PiCLDlN0wkUGY-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S31.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.onKJTzIZowunFZQ0-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S23.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.qN0TocA9AAHxywJY-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S10.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.tdiMdWfixh6fjadZ-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S22.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-bracken_species/1-1-1.xZvD8e7qQi8PUA2N-SHpMEj1q.tsv "$DEST"/taxonomy_reads/bracken_species/S6.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.01HCK9dZAMAbMukq-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S25.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.2xIMBGbiOseSxQCD-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S11.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.4B6fy8hZZ8vSXE6B-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S5.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.4xCV6JRU6HkGatYq-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S20.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.7rMQZ4Ula2DmGaEd-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/NTC.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.9AjOqVTJNROY7DBG-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S2.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.AXK1NbQNocBd4qqI-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S14.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.CNI1jcL33E2M2uV6-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S19.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.E7S5GJo5ekcoOV27-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S33.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.FKp680zKVo15dKgx-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S21.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.IPNSBGNPpc9mx9pb-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S9.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.JY18N2LHdJyyKRwd-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S16.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.Pa6ucpXzUxAcuJtu-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S17.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.QgjOzZ09l9i6knsR-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S1.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.Qr8WER28PwzTwUhF-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S4.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.SE6URQqgwsDooLq4-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S26.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.UuWOdRNf2iRU3a0s-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S3.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.Vneit8ULTahKdRZb-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S29.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.W6RLtc1JWrQak6xQ-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S28.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.X9ogN7cwWyqV1rpF-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S30.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.XRi701FcJjjCcIJE-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S7.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.as0LFV4jcZBVeaAT-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S15.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.btskgvYgpK5TkYCK-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S27.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.mDxVGaoPbZ5795FZ-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S24.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.mEiZZ5B1TErMYJfM-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S18.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.nCeLnPSiD1XZVwqJ-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S13.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.nXQanJEGt3xJDy8L-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S8.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.o3c9CZgtU9S2sjB0-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S32.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.oEtMqfWVbBxXHV95-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S12.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.oP1PiCLDlN0wkUGY-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S31.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.onKJTzIZowunFZQ0-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S23.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.qN0TocA9AAHxywJY-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S10.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.tdiMdWfixh6fjadZ-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S22.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/4_taxonomy-bracken_kreport/1-1-1.xZvD8e7qQi8PUA2N-GRtIgDmU.tsv "$DEST"/taxonomy_reads/bracken_kreport/S6.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.0c6ryb63U9iwcNMQ-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S24.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.28fRCa04qtF7fKyR-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S1.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.439bc1teDfM1Xh9n-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S20.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.4un81LIPOwOfVns4-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S18.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.5l5mGEGow2rbOVQl-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S11.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.7WWrTcBLeTLku6Kf-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S8.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.8MSEef0blHeYv5jI-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/NTC.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.9YgRvd1yUUrEnCjR-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S14.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.ASzGp3FikUvCSeI1-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S26.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.FXMpdMZVoXreYynH-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S28.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.FXUzw6YavmkfL8VT-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S10.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.Fxzn1HbE69HrqGhP-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S21.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.HIf9Dokx54dhfif3-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S3.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.JlzxZwbeosGoCNJt-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S16.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.MsBMpKnBOHHpWeP4-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S6.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.NNyoZTXdWm2HAgXk-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S22.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.OBdPGjAx0bHjVYNS-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S7.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.OLagzcT9G7gpvwju-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S23.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.PUUqZ2VnRpL11taq-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S12.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.WnzuuFCPEnCvCwgu-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S2.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.Xgbxr3gIEwHxmPmK-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S19.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.aOi7XDv1jodLoeTG-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S5.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.iP23sOYqqJi5vqYd-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S4.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.n5PO00ZwFZr5cUCB-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S17.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.pSRHzwXxwgh9HiR8-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S32.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.ubpmBAJp4EcjX09P-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S15.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.wWW9uQ49yIZ5GeXM-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S31.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.xiyEvdNYAYUFhZ5W-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S33.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.xn7pdkPDnqeJBL2t-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S29.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.xu9VFZly1lpfU6l4-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S13.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/3_taxonomy-centrifuger_classifications/1-1-1.zSjcwN1i83ybtX6d-8lecuclo.parquet "$DEST"/taxonomy_reads/centrifuger_classifications/S30.parquet
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.0c6ryb63U9iwcNMQ-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S24.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.28fRCa04qtF7fKyR-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S1.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.439bc1teDfM1Xh9n-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S20.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.4un81LIPOwOfVns4-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S18.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.5l5mGEGow2rbOVQl-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S11.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.7WWrTcBLeTLku6Kf-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S8.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.8MSEef0blHeYv5jI-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/NTC.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.9YgRvd1yUUrEnCjR-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S14.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.ASzGp3FikUvCSeI1-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S26.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.FXMpdMZVoXreYynH-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S28.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.FXUzw6YavmkfL8VT-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S10.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.Fxzn1HbE69HrqGhP-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S21.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.HIf9Dokx54dhfif3-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S3.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.JlzxZwbeosGoCNJt-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S16.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.MsBMpKnBOHHpWeP4-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S6.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.NNyoZTXdWm2HAgXk-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S22.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.OBdPGjAx0bHjVYNS-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S7.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.OLagzcT9G7gpvwju-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S23.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.PUUqZ2VnRpL11taq-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S12.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.WnzuuFCPEnCvCwgu-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S2.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.Xgbxr3gIEwHxmPmK-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S19.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.aOi7XDv1jodLoeTG-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S5.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.iP23sOYqqJi5vqYd-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S4.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.n5PO00ZwFZr5cUCB-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S17.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.pSRHzwXxwgh9HiR8-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S32.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.ubpmBAJp4EcjX09P-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S15.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.wWW9uQ49yIZ5GeXM-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S31.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.xiyEvdNYAYUFhZ5W-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S33.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.xn7pdkPDnqeJBL2t-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S29.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.xu9VFZly1lpfU6l4-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S13.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_kreport/1-1-1.zSjcwN1i83ybtX6d-8Q3EVkm5.tsv "$DEST"/taxonomy_reads/centrifuger_kreport/S30.txt
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.0c6ryb63U9iwcNMQ-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S24.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.28fRCa04qtF7fKyR-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S1.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.439bc1teDfM1Xh9n-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S20.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.4un81LIPOwOfVns4-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S18.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.5l5mGEGow2rbOVQl-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S11.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.7WWrTcBLeTLku6Kf-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S8.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.8MSEef0blHeYv5jI-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/NTC.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.9YgRvd1yUUrEnCjR-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S14.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.ASzGp3FikUvCSeI1-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S26.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.FXMpdMZVoXreYynH-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S28.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.FXUzw6YavmkfL8VT-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S10.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.Fxzn1HbE69HrqGhP-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S21.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.HIf9Dokx54dhfif3-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S3.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.JlzxZwbeosGoCNJt-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S16.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.MsBMpKnBOHHpWeP4-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S6.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.NNyoZTXdWm2HAgXk-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S22.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.OBdPGjAx0bHjVYNS-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S7.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.OLagzcT9G7gpvwju-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S23.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.PUUqZ2VnRpL11taq-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S12.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.WnzuuFCPEnCvCwgu-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S2.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.Xgbxr3gIEwHxmPmK-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S19.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.aOi7XDv1jodLoeTG-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S5.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.iP23sOYqqJi5vqYd-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S4.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.n5PO00ZwFZr5cUCB-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S17.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.pSRHzwXxwgh9HiR8-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S32.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.ubpmBAJp4EcjX09P-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S15.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.wWW9uQ49yIZ5GeXM-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S31.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.xiyEvdNYAYUFhZ5W-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S33.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.xn7pdkPDnqeJBL2t-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S29.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.xu9VFZly1lpfU6l4-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S13.tsv
cp -n /scratch/phyberos/gmcf3495/metasmith/runs/KMQ5eomS/results/taxonomy-centrifuger_summary/1-1-1.zSjcwN1i83ybtX6d-iP7EX2jM.tsv "$DEST"/taxonomy_reads/centrifuger_summary/S30.tsv
