from typing import Callable, Protocol, runtime_checkable

from ..coms.terminals import ShellResult


@runtime_checkable
class Shell(Protocol):
    def Exec(self, cmd: str, timeout=None, history: bool = False) -> ShellResult: ...
    def ExecAsync(self, cmd: str): ...
    def AwaitDone(self, *args, **kwargs): ...
    def RegisterOnOut(self, callback: Callable[[str], None]): ...
    def RegisterOnErr(self, callback: Callable[[str], None]): ...
    def Dispose(self, *args, **kwargs): ...
    def __enter__(self): ...
    def __exit__(self, *args): ...
