# generated by transforms/aspire/_generate.py -- do not hand-edit
"""asv_mag_link_absent -- no .nf process

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run     = model.AddRequirement(lib.GetType("aspire::run"))
policy  = model.AddRequirement(lib.GetType("aspire::asv_mag_link_off"), parents={run})
pairing = model.AddProduct(lib.GetType("aspire::asv_mag_pairing"))
out     = model.AddProduct(lib.GetType("aspire::asv_mag_outputs"))

def protocol(context: ExecutionContext):
    made = {
        pairing: context.Output(pairing),
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
