# generated by transforms/aspire/_generate.py -- do not hand-edit
"""batch_correction_passthrough -- no .nf process

the `off` arm: the uncorrected counts and ASV metadata reach the analyses
unchanged.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run        = model.AddRequirement(lib.GetType("aspire::run"))
policy     = model.AddRequirement(lib.GetType("aspire::batch_correction_off"), parents={run})
am         = model.AddRequirement(lib.GetType("aspire::stage_asv_meta"), parents={run})
counts     = model.AddRequirement(lib.GetType("aspire::asv_final_micro"), parents={run})
out_counts = model.AddProduct(lib.GetType("aspire::analysis_counts"))
out_am     = model.AddProduct(lib.GetType("aspire::analysis_asv_meta"))

def protocol(context: ExecutionContext):
    made = {
        out_counts: context.Output(out_counts),
        out_am: context.Output(out_am),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
