# generated by transforms/aspire/_generate.py -- do not hand-edit
"""chimera_check -- CHIMERA_CHECK (asv_pipeline.nf:3393)

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run       = model.AddRequirement(lib.GetType("aspire::run"))
centroids = model.AddRequirement(lib.GetType("aspire::centroids_fasta"), parents={run})
nochi     = model.AddProduct(lib.GetType("aspire::nochimera_fasta"))

def protocol(context: ExecutionContext):
    made = {
        nochi: context.Output(nochi),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=8,
        memory=Size.GB(16),
        duration=Duration(hours=4),
    ),
)
