# generated by transforms/aspire/_generate.py -- do not hand-edit
"""concat_fastas -- CONCAT_FASTAS (asv_pipeline.nf:3274)

Folded in: RELABEL_FILTERED (asv_pipeline.nf:3248)

r4 collapse: this emitted the same reads twice, differing only in whether the
headers carry the sample label, and vsearch --derep_fulllength does not read
headers -- so one file serves both consumers and `aspire::concat_fasta` is
gone. The row stays: it is the study fan-in, which is a structural event and
not staging. The study fan-in: group_by=run collapses every sample's filtered
reads into one task. RELABEL_FILTERED is folded in -- it is a header rewrite
over a file this transform already reads, and keeping it separate and optional
would add a third rebinding switch for a sed. The real protocol names each
sequence from the sample_id its fasta descends from (context.SourceOf), never
from the position of the file in the group.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run       = model.AddRequirement(lib.GetType("aspire::run"))
sid       = model.AddRequirement(lib.GetType("aspire::sample_id"), parents={run})
filtered  = model.AddRequirement(lib.GetType("aspire::filtered_fasta"), parents={sid})
counts_fa = model.AddProduct(lib.GetType("aspire::concat_counts_fasta"))

def protocol(context: ExecutionContext):
    made = {
        counts_fa: context.Output(counts_fa),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=2,
        memory=Size.GB(4),
        duration=Duration(hours=2),
    ),
)
