# generated by transforms/aspire/_generate.py -- do not hand-edit
"""group_power_analysis -- GROUP_POWER_ANALYSIS (asv_pipeline.nf:5030)

one Nextflow task hiding a bash driver, three Python drivers, six analysis
scripts and an R script. One stub here is honest for a topology pass and is
the clearest candidate for expansion later.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run    = model.AddRequirement(lib.GetType("aspire::run"))
am     = model.AddRequirement(lib.GetType("aspire::analysis_asv_meta"), parents={run})
counts = model.AddRequirement(lib.GetType("aspire::analysis_counts"), parents={run})
tables = model.AddRequirement(lib.GetType("aspire::indicspecies_tables"), parents={run})
out    = model.AddProduct(lib.GetType("aspire::power_analysis_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=8,
        memory=Size.GB(32),
        duration=Duration(hours=12),
    ),
)
