# generated by transforms/aspire/_generate.py -- do not hand-edit
"""master_summary_optional_slot -- no .nf process

asv_pipeline.nf:2792 fills the master summary's optional-contributor slot with
an empty placeholder unconditionally -- there is no arm that fills it with
anything. Ported as a permanent stub so the dead slot is visible in the DAG
rather than hidden in a channel assignment.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run = model.AddRequirement(lib.GetType("aspire::run"))
opt = model.AddProduct(lib.GetType("aspire::optional_outputs"))

def protocol(context: ExecutionContext):
    made = {
        opt: context.Output(opt),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {opt}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=1),
    ),
)
