# generated by transforms/aspire/_generate.py -- do not hand-edit
"""master_summary -- MASTER_SUMMARY (asv_pipeline.nf:5763)

four `.done` barriers plus a --data-dir scan, replaced by four directory-typed
requirements each with an off-arm producer. Which of the merged tables
actually appear is decided at runtime by a config whitelist and stays a
runtime parameter: modelling it in the type system would need one transform
per subset.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run        = model.AddRequirement(lib.GetType("aspire::run"))
am         = model.AddRequirement(lib.GetType("aspire::analysis_asv_meta"), parents={run})
counts     = model.AddRequirement(lib.GetType("aspire::analysis_counts"), parents={run})
net        = model.AddRequirement(lib.GetType("aspire::network_outputs"), parents={run})
sankey     = model.AddRequirement(lib.GetType("aspire::sankey_outputs"), parents={run})
magl       = model.AddRequirement(lib.GetType("aspire::asv_mag_outputs"), parents={run})
opt        = model.AddRequirement(lib.GetType("aspire::optional_outputs"), parents={run})
long       = model.AddProduct(lib.GetType("aspire::master_long"))
wide       = model.AddProduct(lib.GetType("aspire::master_count_wide"))
manifest   = model.AddProduct(lib.GetType("aspire::master_source_manifest"))
colmap     = model.AddProduct(lib.GetType("aspire::master_column_mapping"))
collisions = model.AddProduct(lib.GetType("aspire::master_column_collisions"))

def protocol(context: ExecutionContext):
    made = {
        long: context.Output(long),
        wide: context.Output(wide),
        manifest: context.Output(manifest),
        colmap: context.Output(colmap),
        collisions: context.Output(collisions),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=4,
        memory=Size.GB(32),
        duration=Duration(hours=4),
    ),
)
