# generated by transforms/aspire/_generate.py -- do not hand-edit
"""merge_and_filter_reads -- FILTER_READS (asv_pipeline.nf:3221)

Folded in: MERGE_READS (asv_pipeline.nf:3179)

r4 fold. Two vsearch calls on one sample, back to back: --fastq_mergepairs
then --fastq_filter. The merged pair had exactly one consumer and is not a
target anyone names -- what a reader wants from the merge is its RATE, and
GENERAL_STATS reports that, not this file.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run      = model.AddRequirement(lib.GetType("aspire::run"))
sid      = model.AddRequirement(lib.GetType("aspire::sample_id"), parents={run})
fwd      = model.AddRequirement(lib.GetType("aspire::qc_reads_fwd"), parents={sid})
rev      = model.AddRequirement(lib.GetType("aspire::qc_reads_rev"), parents={sid})
filtered = model.AddProduct(lib.GetType("aspire::filtered_fasta"))

def protocol(context: ExecutionContext):
    made = {
        filtered: context.Output(filtered),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = set()

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=sid,
    resources=Resources(
        cpus=4,
        memory=Size.GB(4),
        duration=Duration(hours=2),
    ),
)
