# generated by transforms/aspire/_generate.py -- do not hand-edit
"""paired_group_contrast -- PAIRED_GROUP_CONTRAST (asv_pipeline.nf:5234)

r4 ecology lift: requires the generic `amplicon::survey` grouping node and a
bare `amplicon::asv_table` instead of `aspire::run` and
`aspire::analysis_counts`, so it is reachable from any count table --
`kbase/profile_abundance/kraken_abundance.py` produces one from kraken2
reports. An ASPIRE run satisfies the survey requirement unchanged. See
research/kbase/curation/r4/aspire_topology.md.

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
survey = model.AddRequirement(lib.GetType("amplicon::survey"))
counts = model.AddRequirement(lib.GetType("amplicon::asv_table"), parents={survey})
am     = model.AddRequirement(lib.GetType("aspire::analysis_asv_meta"), parents={survey})
out    = model.AddProduct(lib.GetType("aspire::paired_group_contrast_outputs"))

def protocol(context: ExecutionContext):
    made = {
        out: context.Output(out),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {out}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=survey,
    resources=Resources(
        cpus=4,
        memory=Size.GB(16),
        duration=Duration(hours=4),
    ),
)
