# generated by transforms/aspire/_generate.py -- do not hand-edit
"""prepare_blast_databases -- PREPARE_BLAST_DATABASES (asv_pipeline.nf:3511)

Stub: the model is the port, the body only touches its outputs.
Regenerate with `python transforms/aspire/_generate.py`.
"""

from metasmith.python_api import *

lib   = TransformInstanceLibrary.ResolveParentLibrary(__file__)
model = Transform()
run      = model.AddRequirement(lib.GetType("aspire::run"))
mito_src = model.AddRequirement(lib.GetType("aspire::mito_reference_source"))
cont_src = model.AddRequirement(lib.GetType("aspire::contaminant_reference_source"))
mito_db  = model.AddProduct(lib.GetType("aspire::mito_blast_db"))
cont_db  = model.AddProduct(lib.GetType("aspire::contaminant_blast_db"))

def protocol(context: ExecutionContext):
    made = {
        mito_db: context.Output(mito_db),
        cont_db: context.Output(cont_db),
    }
    for key, path in made.items():
        make = 'mkdir -p' if key in _DIRECTORY_PRODUCTS else 'touch'
        context.external_shell.Exec(f'{make} {path.external}')
    return ExecutionResult(
        manifest=[{k: v.local for k, v in made.items()}],
        success=all(v.local.exists() for v in made.values()),
    )

_DIRECTORY_PRODUCTS = {mito_db, cont_db}

TransformInstance(
    protocol=protocol,
    model=model,
    group_by=run,
    resources=Resources(
        cpus=1,
        memory=Size.GB(4),
        duration=Duration(hours=2),
    ),
)
