"""The on-wire lin-envelope version must stay synced across its two writers.

There are two independent statements of the Nextflow-channel lin-envelope
version, and a real task fails at runtime the moment they disagree:

  1. the PARSER — `models.lineage.LinPayload` (`VERSION` / `Unpack`), which
     rejects any payload whose `v` != `LIN_PAYLOAD_VERSION`; and
  2. the EMITTER — a Groovy literal generated by `workflow.py` into every
     compiled `workflow.nf`:
        echo "lin ${Orchestrator.JsonforEcho([v:N, entries:index])}"

These live in different files and are NOT type-checked against each other.
The fast test suite cannot catch a desync because its harnesses synthesize
lin payloads via `json.dumps`, never through the Groovy wire — so a mismatch
only surfaces in a real docker/apptainer deploy, where it fails EVERY task
with `unsupported lin payload version <emitted>; expected <parser>`.

That is exactly what happened in R5: bumping the (then-shared) version
constant for the F1 cache-key change moved the parser to 3 while the Groovy
emitter stayed hardcoded at 2. The cache-key epoch and the wire version are
now separate constants (`CACHE_KEY_VERSION` vs `LIN_PAYLOAD_VERSION`).

The emitter no longer spells the version as a literal — it interpolates
`LIN_PAYLOAD_VERSION` into `nextflow_codegen.LIN_ECHO_EXPR`, so the desync is
unrepresentable rather than merely detected. These tests pin that: the
rendered expression must stamp the parser's version, and no module in the
workflow package may reintroduce a hardcoded one.
"""

from __future__ import annotations

import re
from pathlib import Path

from metasmith.caching.keys import CACHE_KEY_VERSION, LIN_PAYLOAD_VERSION
from metasmith.models.lineage import LinPayload
from metasmith.models.workflow.nextflow_codegen import LIN_ECHO_EXPR
import metasmith.models.workflow as workflow_mod


# `[v:2, entries:...]` — the version the Groovy emitter stamps onto the wire.
_EMITTER_RE = re.compile(r"\[\s*v\s*:\s*(\d+)\s*,\s*entries\s*:")


def _hardcoded_wire_versions() -> list[int]:
    # Scan the whole package, not one module. The emitter used to sit in
    # workflow.py; it now lives in workflow/nextflow_codegen.py, and reading
    # `workflow_mod.__file__` after the split would have read an __init__ of
    # pure re-exports -- no literals, and this guard blind to the one desync
    # it exists to catch. Globbing keeps it honest through the next move too.
    pkg = Path(workflow_mod.__file__).parent
    found: list[int] = []
    for src in sorted(pkg.rglob("*.py")):
        found += [int(m) for m in _EMITTER_RE.findall(src.read_text(encoding="utf-8"))]
    return found


def test_rendered_emitter_stamps_the_parser_version():
    """The expression the compiler emits carries `LIN_PAYLOAD_VERSION`."""
    found = _EMITTER_RE.findall(LIN_ECHO_EXPR)
    assert found, (
        f"no `[v:N, entries:...]` envelope in the rendered emitter "
        f"{LIN_ECHO_EXPR!r}; the guard is stale — update it to track the "
        f"current emitter so this invariant keeps being checked"
    )
    for n in found:
        assert int(n) == LIN_PAYLOAD_VERSION, (
            f"Groovy lin emitter stamps wire version {n} but the parser "
            f"(LinPayload) expects {LIN_PAYLOAD_VERSION}; a real deploy would "
            f"fail every task with 'unsupported lin payload version'."
        )


def test_no_module_hardcodes_the_wire_version():
    """The version must be interpolated, never typed as a literal."""
    assert _hardcoded_wire_versions() == [], (
        "a module in metasmith.models.workflow spells the lin-envelope "
        "version as a literal. Interpolate LIN_PAYLOAD_VERSION instead — a "
        "literal is how R5 desynced the emitter from the parser and failed "
        "every containerized task with a green fast suite."
    )


def test_parser_classvar_tracks_module_constant():
    """LinPayload.VERSION must equal the wire constant it is built from."""
    assert LinPayload.VERSION == LIN_PAYLOAD_VERSION


def test_cache_epoch_and_wire_version_are_independent():
    """The two concerns are separate constants (regression guard for R5).

    They are not required to hold any particular relative value — only to be
    distinct symbols so a cache-semantics bump never again drags the wire
    version (and its un-synced Groovy emitter) along with it. Pinning the
    known values documents the split and flags any accidental re-merge. They
    have now moved independently at least once -- the wire went to 4 to carry
    per-item provenance while the cache epoch stayed at 3, because no cache key
    changed and existing shards stay valid -- which is the split doing its job.
    """
    assert CACHE_KEY_VERSION == 3
    assert LIN_PAYLOAD_VERSION == 4
    assert CACHE_KEY_VERSION != LIN_PAYLOAD_VERSION, (
        "the two constants having drifted apart is the point; if a change ever "
        "makes them equal again, it must be a coincidence and not a re-merge"
    )


# -- reserved index keys -----------------------------------------------------
#
# `FILES` and `PROV` are the second cross-language pair on this wire: the
# Groovy Orchestrator writes them into the index and strips them again, and
# Python reads them back by name. They have exactly the failure mode the
# version constant had -- two spellings in two languages that nothing checks
# against each other -- so they get the same guard.

_GROOVY_KEY_RE = re.compile(
    r"public\s+static\s+final\s+String\s+(FILES_KEY|PROV_KEY)\s*=\s*\"([^\"]+)\""
)


def _orchestrator_source() -> str:
    src = Path(workflow_mod.__file__).parents[2] / "nextflow_config" / "Orchestrator.groovy"
    assert src.is_file(), f"Orchestrator.groovy not found at [{src}]"
    return src.read_text()


def test_groovy_reserved_keys_match_the_parser():
    """The Orchestrator's reserved key names must equal LinPayload's."""
    found = dict(_GROOVY_KEY_RE.findall(_orchestrator_source()))
    assert found == {"FILES_KEY": LinPayload.FILES_KEY, "PROV_KEY": LinPayload.PROV_KEY}, (
        f"Orchestrator.groovy declares {found}, but the parser expects "
        f"FILES_KEY={LinPayload.FILES_KEY!r} PROV_KEY={LinPayload.PROV_KEY!r}. "
        "A renamed key on one side leaves the other reading a key nobody writes: "
        "FILES silently empties every input group, PROV silently disables "
        "provenance. Neither raises."
    )


def test_reserved_keys_are_the_set_lineage_index_filters():
    """RESERVED_KEYS must be exactly the keys the Orchestrator injects.

    A key added to one and not the other is how a nested value reaches
    `promote`'s shard manifest and then the cache-hit `.nf` literal, which
    stringifies it into silent garbage rather than failing.
    """
    assert LinPayload.RESERVED_KEYS == {LinPayload.FILES_KEY, LinPayload.PROV_KEY}


def test_the_orchestrator_strips_every_reserved_key_on_the_way_out():
    """_debatch must strip each reserved key, or it propagates forever.

    A key left in rides into every descendant index through `_post`, grows
    without bound, and lands in promoted shard manifests.

    The strip lives in `stripReserved` rather than inline so it can be raced
    directly in the orchestrator exec suite, so this checks the two halves:
    `_debatch` routes every index through it, and it names both keys.
    """
    src = _orchestrator_source()
    debatch = src.split("public def _debatch(")[1]
    assert "stripReserved(index)" in debatch, (
        "_debatch no longer routes its indexes through stripReserved; the "
        "strip is what keeps FILES and PROV out of every downstream index"
    )
    strip = src.split("public static Map stripReserved(")[1].split("\n    }\n")[0]
    for key in ("FILES_KEY", "PROV_KEY"):
        assert key in strip, (
            f"stripReserved does not strip {key}; it will propagate into "
            "every downstream index and into promoted shards"
        )
